# DATABASE CONFIG FOR DOCKER COMPOSE
spring.datasource.url=jdbc:postgresql://localhost:5432/tanninsdb
spring.datasource.username=tanninsdb
spring.datasource.password=tanninsdb

# ORCID DUMMY VALUES (Not used when using /auth/dev)
orcid.client-id=dev_client_id
orcid.client-secret=dev_client_secret
orcid.redirect-uri=http://localhost:8080/auth/orcid/callback

# JWT CONFIG
security.jwt.secret-key=ZDJiM2U0YjVjNjY0OGQ5Yjg4OTk0NjY5N2U4YjYyZDU4ZDJiM2U0YjVjNjY0OGQ5Yjg4OTk0NjY5N2U4YjYyZDU=
security.jwt.expiration-time=86400000
